// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQbn7aEnXOFsWJ0sOuw_eJdQDnsb8wDA',
    appId: '1:375512734410:web:06f78964882327ef647233',
    messagingSenderId: '375512734410',
    projectId: 'nurseapp-b0add',
    authDomain: 'nurseapp-b0add.firebaseapp.com',
    storageBucket: 'nurseapp-b0add.firebasestorage.app',
    measurementId: 'G-8421849FWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQEFx0mYeHwO86kwGktoQ0WFQ0b1yJRjQ',
    appId: '1:375512734410:android:8f313aacfb947b3f647233',
    messagingSenderId: '375512734410',
    projectId: 'nurseapp-b0add',
    storageBucket: 'nurseapp-b0add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2MsNf27QaM2_e9I36V2kU9aueKUupCyM',
    appId: '1:375512734410:ios:96988d6f5eee9a3d647233',
    messagingSenderId: '375512734410',
    projectId: 'nurseapp-b0add',
    storageBucket: 'nurseapp-b0add.firebasestorage.app',
    iosBundleId: 'com.example.nurseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2MsNf27QaM2_e9I36V2kU9aueKUupCyM',
    appId: '1:375512734410:ios:96988d6f5eee9a3d647233',
    messagingSenderId: '375512734410',
    projectId: 'nurseapp-b0add',
    storageBucket: 'nurseapp-b0add.firebasestorage.app',
    iosBundleId: 'com.example.nurseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMQbn7aEnXOFsWJ0sOuw_eJdQDnsb8wDA',
    appId: '1:375512734410:web:8202548aa72f815e647233',
    messagingSenderId: '375512734410',
    projectId: 'nurseapp-b0add',
    authDomain: 'nurseapp-b0add.firebaseapp.com',
    storageBucket: 'nurseapp-b0add.firebasestorage.app',
    measurementId: 'G-Q9QNMR4TYE',
  );
}
